CREATE SCHEMA IF NOT EXISTS workflows;

CREATE TABLE IF NOT EXISTS workflows.vulnerabilities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id bigint NOT NULL,
    workflow_id bigint NOT NULL,
    scan_metadata_id bigint NOT NULL,
    prev_id bigint NOT NULL,
    json_answer jsonb, -- must include: explanation, file_path, line, malicious_input_example, summary, trigger_flow, vulnerability_type, malicious_actor
    post_script_answer jsonb,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    prev_table text,
    comments text,
    interesting bigint,
    repeat_run integer,
    rank integer,
    dedupe_run_id numeric,
    dedupe_model text,
    dedupe_is_canonical boolean,
    dedupe_canonical_id bigint,
    dedupe_cluster_id text,
    dedupe_reason text,
    bounty_rank_response jsonb,
    bounty_rank integer,
    bounty_rank_impact_level text,
    bounty_rank_minimum_reward bigint,
    bounty_rank_maximum_reward bigint,
    bounty_rank_reasoning text,
    rank_root_bug text,
    bounty_rank_missing_from_prompt text,
    bounty_rank_total_issues integer,
    bounty_rank_run_id bigint,
    bounty_rank_model text,
    bounty_rank_ts timestamp with time zone
);

CREATE TABLE IF NOT EXISTS workflows.step_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    step_id bigint NOT NULL,
    scan_id bigint NOT NULL,
    workflow_id bigint NOT NULL,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    partition_key text NOT NULL, -- generated by `{scan_id}-{step_depth}`
    prev_id bigint,
    prev_table text,
    repeat_run integer,
    json_answer jsonb,
    PRIMARY KEY (partition_key, id)
) PARTITION BY LIST (partition_key);

CREATE TABLE IF NOT EXISTS workflows.step_results_default
    PARTITION OF workflows.step_results DEFAULT;

ALTER TABLE workflows.step_results_default
    ALTER COLUMN id SET DEFAULT nextval(pg_get_serial_sequence('workflows.step_results', 'id'));

CREATE INDEX IF NOT EXISTS step_results_partition_key_idx
    ON workflows.step_results USING btree (partition_key);

CREATE TABLE IF NOT EXISTS workflows.step_metadata (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id bigint NOT NULL,
    workflow_id numeric,
    step_id bigint NOT NULL,
    prev_id bigint,
    prev_table text,
    repeat_run integer,
    status text,
    phase text,
    error text,
    kind text DEFAULT 'step' NOT NULL,
    post_process_metadata_id bigint,
    post_script_id bigint,
    post_script_name text,
    vulnerability_id bigint,
    target_vulnerability_ids bigint[] DEFAULT ARRAY[]::bigint[] NOT NULL,
    batch_index integer,
    stub boolean DEFAULT false NOT NULL,
    prompt_template text,
    prompt_filled text,
    output_json jsonb,
    checked_out_commit text,
    run_started_at timestamp with time zone,
    run_time_ms numeric,
    raw_token_usage jsonb,
    token_count_cached_input jsonb,
    token_count_input jsonb,
    token_count_output jsonb,
    token_count_reasoning_output jsonb,
    token_count_total jsonb,
    codex_session_id text,
    codex_source_home text,
    codex_account_id text,
    codex_account_email text,
    model text,
    harness text,
    thinking_effort text,
    model_provider text,
    subagent_count integer DEFAULT 0 NOT NULL,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS workflows.triage (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vulnerability_id bigint NOT NULL,
    post_script_id bigint NOT NULL,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS workflows.vulnerability_enrichments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id bigint NOT NULL,
    vulnerability_id bigint NOT NULL,
    post_script_id bigint NOT NULL,
    post_script_name text NOT NULL,
    result jsonb,
    stub boolean DEFAULT false NOT NULL,
    stub_explanation text,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE (vulnerability_id, post_script_id)
);

CREATE TABLE IF NOT EXISTS workflows.post_process_metadata (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id bigint NOT NULL,
    workflow_id bigint,
    post_script_id bigint,
    post_script_name text,
    vulnerability_id bigint,
    kind text NOT NULL,
    batch_index integer,
    target_vulnerability_ids bigint[] DEFAULT ARRAY[]::bigint[] NOT NULL,
    status text NOT NULL,
    phase text,
    error text,
    prompt_template text,
    prompt_filled text,
    output_json jsonb,
    checked_out_commit text,
    run_started_at timestamp with time zone,
    run_time_ms numeric,
    raw_token_usage jsonb,
    token_count_cached_input jsonb,
    token_count_input jsonb,
    token_count_output jsonb,
    token_count_reasoning_output jsonb,
    token_count_total jsonb,
    codex_session_id text,
    codex_source_home text,
    codex_account_id text,
    codex_account_email text,
    model text,
    harness text,
    thinking_effort text,
    model_provider text,
    subagent_count integer DEFAULT 0 NOT NULL,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS vulnerabilities_dedupe_idx
    ON workflows.vulnerabilities USING btree (scan_id, dedupe_is_canonical, dedupe_canonical_id);

CREATE INDEX IF NOT EXISTS vulnerabilities_bounty_rank_idx
    ON workflows.vulnerabilities USING btree (scan_id, bounty_rank);

CREATE INDEX IF NOT EXISTS vulnerability_enrichments_scan_idx
    ON workflows.vulnerability_enrichments USING btree (scan_id);

CREATE INDEX IF NOT EXISTS vulnerability_enrichments_vulnerability_idx
    ON workflows.vulnerability_enrichments USING btree (vulnerability_id);

CREATE INDEX IF NOT EXISTS post_process_metadata_scan_idx
    ON workflows.post_process_metadata USING btree (scan_id, kind, status);

CREATE INDEX IF NOT EXISTS post_process_metadata_vulnerability_idx
    ON workflows.post_process_metadata USING btree (vulnerability_id, kind, post_script_id);

CREATE INDEX IF NOT EXISTS step_metadata_kind_scan_idx
    ON workflows.step_metadata USING btree (kind, scan_id, status);

CREATE UNIQUE INDEX IF NOT EXISTS step_metadata_post_process_metadata_unique
    ON workflows.step_metadata USING btree (post_process_metadata_id)
    WHERE kind <> 'step' AND post_process_metadata_id IS NOT NULL;


CREATE TABLE IF NOT EXISTS public.steps (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text NOT NULL,
    output_format text NOT NULL,
    name text, -- optional name for the step
    depth integer NOT NULL,
    multi_output boolean NOT NULL,
    is_last_step boolean NOT NULL,
    output_table text NOT NULL, -- for the last step, the output table should be workflows.vulnerabilities
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.post_scripts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text NOT NULL,
    output_format text NOT NULL,
    name text NOT NULL,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.llm_workflows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_ids bigint[] DEFAULT ARRAY[]::bigint[] NOT NULL,
    name text NOT NULL,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.scans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id bigint NOT NULL,
    post_script_id bigint NOT NULL,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    repo_full text NOT NULL,
    commit_sha text NOT NULL,
    repo_scope text NOT NULL,
    dependencies text[] NOT NULL,
    configuration jsonb NOT NULL,
    model text NOT NULL,
    model_provider text DEFAULT 'openrouter'::text NOT NULL,
    harness text NOT NULL,
    status text NOT NULL, -- queued, pending, prewarming_cache, running, rate_limited, paused, post_processing, completed, stopped, failed
    config jsonb DEFAULT '{}'::jsonb NOT NULL, -- legacy compatibility JSON; scan columns are authoritative
    scopes jsonb NOT NULL, -- must include: files, lines
    reasoning jsonb
);
