ALTER TABLE workflows.vulnerabilities
    ADD COLUMN IF NOT EXISTS dedupe_run_id numeric,
    ADD COLUMN IF NOT EXISTS dedupe_model text,
    ADD COLUMN IF NOT EXISTS dedupe_is_canonical boolean,
    ADD COLUMN IF NOT EXISTS dedupe_canonical_id bigint,
    ADD COLUMN IF NOT EXISTS dedupe_cluster_id text,
    ADD COLUMN IF NOT EXISTS dedupe_reason text,
    ADD COLUMN IF NOT EXISTS bounty_rank_response jsonb,
    ADD COLUMN IF NOT EXISTS bounty_rank integer,
    ADD COLUMN IF NOT EXISTS bounty_rank_impact_level text,
    ADD COLUMN IF NOT EXISTS bounty_rank_minimum_reward bigint,
    ADD COLUMN IF NOT EXISTS bounty_rank_maximum_reward bigint,
    ADD COLUMN IF NOT EXISTS bounty_rank_reasoning text,
    ADD COLUMN IF NOT EXISTS rank_root_bug text,
    ADD COLUMN IF NOT EXISTS bounty_rank_missing_from_prompt text,
    ADD COLUMN IF NOT EXISTS bounty_rank_total_issues integer,
    ADD COLUMN IF NOT EXISTS bounty_rank_run_id bigint,
    ADD COLUMN IF NOT EXISTS bounty_rank_model text,
    ADD COLUMN IF NOT EXISTS bounty_rank_ts timestamp with time zone;

CREATE INDEX IF NOT EXISTS vulnerabilities_dedupe_idx
    ON workflows.vulnerabilities USING btree (scan_id, dedupe_is_canonical, dedupe_canonical_id);

CREATE INDEX IF NOT EXISTS vulnerabilities_bounty_rank_idx
    ON workflows.vulnerabilities USING btree (scan_id, bounty_rank);

CREATE TABLE IF NOT EXISTS workflows.vulnerability_enrichments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id bigint NOT NULL,
    vulnerability_id bigint NOT NULL,
    post_script_id bigint NOT NULL,
    post_script_name text NOT NULL,
    result jsonb,
    stub boolean DEFAULT false NOT NULL,
    stub_explanation text,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE (vulnerability_id, post_script_id)
);

CREATE INDEX IF NOT EXISTS vulnerability_enrichments_scan_idx
    ON workflows.vulnerability_enrichments USING btree (scan_id);

CREATE INDEX IF NOT EXISTS vulnerability_enrichments_vulnerability_idx
    ON workflows.vulnerability_enrichments USING btree (vulnerability_id);

CREATE TABLE IF NOT EXISTS workflows.post_process_metadata (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id bigint NOT NULL,
    workflow_id bigint,
    post_script_id bigint,
    post_script_name text,
    vulnerability_id bigint,
    kind text NOT NULL,
    batch_index integer,
    target_vulnerability_ids bigint[] DEFAULT ARRAY[]::bigint[] NOT NULL,
    status text NOT NULL,
    phase text,
    error text,
    prompt_template text,
    prompt_filled text,
    output_json jsonb,
    checked_out_commit text,
    run_started_at timestamp with time zone,
    run_time_ms numeric,
    raw_token_usage jsonb,
    token_count_cached_input jsonb,
    token_count_input jsonb,
    token_count_output jsonb,
    token_count_reasoning_output jsonb,
    token_count_total jsonb,
    codex_session_id text,
    codex_source_home text,
    codex_account_id text,
    codex_account_email text,
    model text,
    harness text,
    thinking_effort text,
    model_provider text,
    subagent_count integer DEFAULT 0 NOT NULL,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS post_process_metadata_scan_idx
    ON workflows.post_process_metadata USING btree (scan_id, kind, status);

CREATE INDEX IF NOT EXISTS post_process_metadata_vulnerability_idx
    ON workflows.post_process_metadata USING btree (vulnerability_id, kind, post_script_id);
