-- 013_agent_skills.sql
-- Reusable agent skills selected per scan and materialized into executor homes.

CREATE TABLE IF NOT EXISTS public.agent_skills (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    description text,
    content text NOT NULL,
    source_url text,
    license_spdx text,
    attribution text,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.scans
    ADD COLUMN IF NOT EXISTS agent_skill_ids bigint[] DEFAULT ARRAY[]::bigint[];

UPDATE public.scans
SET agent_skill_ids = ARRAY[]::bigint[]
WHERE agent_skill_ids IS NULL;

ALTER TABLE public.scans
    ALTER COLUMN agent_skill_ids SET DEFAULT ARRAY[]::bigint[],
    ALTER COLUMN agent_skill_ids SET NOT NULL;

CREATE INDEX IF NOT EXISTS scans_agent_skill_ids_idx
    ON public.scans USING gin (agent_skill_ids);

