-- 016_severity_rankers.sql
-- Reusable severity-ranking rule sets. Each ranker is a markdown block of rules
-- the model uses to assign a finding's severity (critical, high, medium, low,
-- informational). When creating a scan, the user picks one or more pre-built
-- rankers and/or writes scan-specific rules; the final concatenated string is
-- stored on the scan in scans.severity_ranker. Additive + idempotent.

CREATE TABLE IF NOT EXISTS public.severity_rankers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text,
    content text NOT NULL,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.scans
    ADD COLUMN IF NOT EXISTS severity_ranker text;
