-- Durable queue for natural-language workflow and post-script generation.
-- The engine owns status/result writes; generated resources are only persisted
-- through the existing workflow/post-script APIs after explicit user review.

CREATE TABLE IF NOT EXISTS public.generations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind text NOT NULL CHECK (kind IN ('workflow', 'post_script')),
    request text NOT NULL CHECK (length(btrim(request)) BETWEEN 1 AND 20000),
    model text NOT NULL CHECK (length(btrim(model)) BETWEEN 1 AND 200),
    model_provider text NOT NULL CHECK (model_provider IN ('codex', 'claude', 'openrouter')),
    harness text NOT NULL CHECK (harness IN ('codex', 'claude-code')),
    thinking_effort text DEFAULT 'medium' NOT NULL CHECK (thinking_effort IN ('low', 'medium', 'high', 'xhigh')),
    status text DEFAULT 'pending' NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed')),
    result jsonb CHECK (result IS NULL OR jsonb_typeof(result) = 'object'),
    error text,
    validation_errors jsonb,
    raw_token_usage jsonb,
    codex_session_id text,
    run_started_at timestamp with time zone,
    completed_at timestamp with time zone,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CHECK (
        (model_provider = 'codex' AND harness = 'codex') OR
        (model_provider = 'claude' AND harness = 'claude-code') OR
        model_provider = 'openrouter'
    )
);

CREATE INDEX IF NOT EXISTS generations_status_inserted_at_idx
    ON public.generations USING btree (status, inserted_at);
