-- Durable, additive post-script executions requested after a scan has stopped
-- running. Each run snapshots the selected script so queued work is insulated
-- from later edits or deletion.

CREATE TABLE IF NOT EXISTS workflows.supplemental_post_script_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id bigint NOT NULL,
    post_script_id bigint NOT NULL,
    post_script_name text NOT NULL,
    post_script_content text NOT NULL,
    post_script_output_format text NOT NULL,
    model text,
    model_provider text,
    harness text,
    thinking_effort text,
    extra jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text DEFAULT 'queued' NOT NULL,
    target_count integer DEFAULT 0 NOT NULL,
    completed_count integer DEFAULT 0 NOT NULL,
    failed_count integer DEFAULT 0 NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT supplemental_post_script_runs_status_check
        CHECK (status IN ('queued', 'running', 'completed', 'completed_with_errors'))
);

ALTER TABLE workflows.supplemental_post_script_runs
    ADD COLUMN IF NOT EXISTS model text,
    ADD COLUMN IF NOT EXISTS model_provider text,
    ADD COLUMN IF NOT EXISTS harness text,
    ADD COLUMN IF NOT EXISTS thinking_effort text;

CREATE INDEX IF NOT EXISTS supplemental_post_script_runs_scan_idx
    ON workflows.supplemental_post_script_runs USING btree (scan_id, inserted_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS supplemental_post_script_runs_status_idx
    ON workflows.supplemental_post_script_runs USING btree (status, inserted_at, id);

CREATE TABLE IF NOT EXISTS workflows.supplemental_post_script_targets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint NOT NULL,
    scan_id bigint NOT NULL,
    vulnerability_id bigint NOT NULL,
    status text DEFAULT 'pending' NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    available_at timestamp with time zone DEFAULT now() NOT NULL,
    error text,
    post_process_metadata_id bigint,
    enrichment_id bigint,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT supplemental_post_script_targets_status_check
        CHECK (status IN ('pending', 'running', 'completed', 'failed')),
    CONSTRAINT supplemental_post_script_targets_run_vulnerability_key
        UNIQUE (run_id, vulnerability_id)
);

CREATE INDEX IF NOT EXISTS supplemental_post_script_targets_queue_idx
    ON workflows.supplemental_post_script_targets USING btree (status, available_at, run_id, id);

CREATE INDEX IF NOT EXISTS supplemental_post_script_targets_scan_idx
    ON workflows.supplemental_post_script_targets USING btree (scan_id, vulnerability_id, id);

ALTER TABLE workflows.vulnerability_enrichments
    ADD COLUMN IF NOT EXISTS supplemental_run_id bigint;

ALTER TABLE workflows.vulnerability_enrichments
    DROP CONSTRAINT IF EXISTS vulnerability_enrichments_vulnerability_id_post_script_id_key;

CREATE UNIQUE INDEX IF NOT EXISTS vulnerability_enrichments_regular_unique
    ON workflows.vulnerability_enrichments USING btree (vulnerability_id, post_script_id)
    WHERE supplemental_run_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS vulnerability_enrichments_supplemental_unique
    ON workflows.vulnerability_enrichments USING btree (supplemental_run_id, vulnerability_id)
    WHERE supplemental_run_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS vulnerability_enrichments_supplemental_run_idx
    ON workflows.vulnerability_enrichments USING btree (supplemental_run_id)
    WHERE supplemental_run_id IS NOT NULL;

ALTER TABLE workflows.post_process_metadata
    ADD COLUMN IF NOT EXISTS supplemental_run_id bigint;

ALTER TABLE workflows.step_metadata
    ADD COLUMN IF NOT EXISTS supplemental_run_id bigint;

UPDATE workflows.supplemental_post_script_runs r
SET model = coalesce(r.model, metadata.model),
    model_provider = coalesce(r.model_provider, metadata.model_provider),
    harness = coalesce(r.harness, metadata.harness),
    thinking_effort = coalesce(r.thinking_effort, metadata.thinking_effort)
FROM (
    SELECT DISTINCT ON (supplemental_run_id)
        supplemental_run_id,
        model,
        model_provider,
        harness,
        thinking_effort
    FROM workflows.post_process_metadata
    WHERE supplemental_run_id IS NOT NULL
    ORDER BY supplemental_run_id, id ASC
) metadata
WHERE r.id = metadata.supplemental_run_id
  AND (r.model IS NULL OR r.model_provider IS NULL OR r.harness IS NULL OR r.thinking_effort IS NULL);

CREATE INDEX IF NOT EXISTS post_process_metadata_supplemental_run_idx
    ON workflows.post_process_metadata USING btree (supplemental_run_id, vulnerability_id, status)
    WHERE supplemental_run_id IS NOT NULL;

COMMENT ON TABLE workflows.supplemental_post_script_runs IS
    'User-requested post-script runs over selected findings after normal scan execution.';

COMMENT ON COLUMN workflows.vulnerability_enrichments.supplemental_run_id IS
    'Non-null for additive enrichment produced by a supplemental post-script run.';
